# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4cbf8edc62b3109df5379db5f444f254"
name = "test"
handle = "test-14462"
application_url = "https://success-words-prev-fitted.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "q-abe-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://success-words-prev-fitted.trycloudflare.com/auth/callback",
  "https://success-words-prev-fitted.trycloudflare.com/auth/shopify/callback",
  "https://success-words-prev-fitted.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
