# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "075f89f33fabdd07a2803198ecf1ca20"
name = "temp-look"
handle = "temp-look"
application_url = "https://norton-col-tan-put.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "q-abe-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://norton-col-tan-put.trycloudflare.com/auth/callback",
  "https://norton-col-tan-put.trycloudflare.com/auth/shopify/callback",
  "https://norton-col-tan-put.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
